### ISSUE TITLE
"Lost connection..."-error when test running patches on WSL2

### ISSUE THREAD

**Issue by johe96** [cmajor-lang/cmajor#28]
I've just started using Cmajor but I've been running code in Windows Subsystem for Linux (WSL2) for the most part and I would always get ``Lost connection to the Cmajor Server process!``  when testing out the demo patches provided by the VSCode extension.

Switching back to Windows and this problem would be non-existent, the demo patches will run as intended.

I'm not entirely clear as to what the reason is. Is it just not supported for WSL?

**Comment by julianstorer** [comment]
That means that the server process can't run (or has crashed). WSL isn't one of our targets, and we've never actually tested on it, so I wouldn't be surprised if it's not one of our supported platforms.

We'll have a look and see what we can do (and we should also try to detect when the platform isn't supported so we can give a better error message there..)

**Comment by cesaref** [comment]
Thanks for the heads up. I'd not considered running the tooling via WSL, so this is something we can investigate.

**Comment by johe96** [comment]
Alright! Thanks for the quick reply! I reckon that It was something amiss on my end since no one had any similar type problems in either Discord or the Issue page on here. 

Keep up the good work!

**Comment by johe96** [comment]
> Just looking at old open issues... Is this something that has been resolved? Now that everything is open-source, maybe if you're trying to use it on a platform that we don't test, you could dig around yourself and look for some clues?

Hi! No I haven't resolved the issue yet but I'll report back if I do more testing using WSL

**Comment by EwaFuss** [comment]
I have that same issue on MacOS. When creating a new patch or even opening an example patch I get the message "Lost connection to the Cmajor server process!". The output window says: "libc++abi: terminating due to uncaught exception of type cmaj::AbortCompilationException" but I don't know what causes the exception and how to fix it. 

I am on a MacBook Pro 2019 i9 using MacOS Sonoma 14.4.1. I have installed the VS Code extension on windows and everything works perfectly but on MacOS I can't get it to work. Any ideas what is happening?

**Comment by julianstorer** [comment]
If the compiler crashes, the UI loses connection to it, and you see the message "connection lost". But these crashes could be caused by anything, so don't assume that your problem is related to other ones on this thread just because you all saw the same message!

(We should probably change the message to say "compiler has crashed" or something to make that clearer!)

If you see a crash like this, and have some code that makes it happen and can show us how to reproduce it, please open a new issue and we can dig into it. 

But also: we're constantly fixing things, so make sure you're seeing this with the very latest Cmajor build.

**Comment by EwaFuss** [comment]
Thank you @julianstorer ! That is what I have assumed. A clearer message would be helpful. 
I do not know why compiling using the VS Code extension does not work while compiling using terminal commands does. Even the demo projects right out of the box cannot be compiled using the VS Code extension but using the terminal commands.
Do you have any clue why that is the case?

**Comment by julianstorer** [comment]
It sounds like you're running an old version, or something has gone wrong in the extension's installation? Have you tried removing and re-installing the extension?
