### ISSUE TITLE
C API

### ISSUE THREAD

**Issue by 0xchase** [cmajor-lang/cmajor#35]
Happy to see the compiler has been open sourced!

I was looking into generating bindings to the cmajor API to interop with other languages and ran into a few hurdles. Since `API/` is all C++ I assumed the best approach would be to build bindings to `COM/`, but it seems that this interface is implemented in C++ as well, which would preclude automatic binding generation with something like [bindgen](https://github.com/rust-lang/rust-bindgen) or [ffigen](https://github.com/dart-lang/ffigen). Furthermore, it looks like the COM interface returns C++ data structures like `choc::com::Ptr<ProgramInterface>`, which again would make interop complicated and potentially bug-prone.

Obviously, I could implement my own C wrapper or reverse engineer the in-memory representation of the data structures returned by the COM API, but it seems to me like having an included C API would benefit the community. If it was me I would have designed the COM API to return C types and added the choc C++ abstractions in `API/`, but perhaps there's a reason I'm not aware of that the compiler must return smart pointers, or perhaps you all had a better approach to interop in mind.

If there's interest in adding a C API I'd be happy to implement it with some guidance on the design. If there's a better approach to interop, let me know that as well.

**Comment by julianstorer** [comment]
Hi there, great that you'd like to get stuck in!

Which languages are you aiming to target?

You won't find any C fans over here, and the idea of adding a clunky C API that we'd need to keep in sync with our C++ one makes me shudder..

But.. I've never used bindgen or ffgen, and my instinct here would be that since our COM classes just follow the standard pattern, then it probably wouldn't take much of a tweak to make our classes compatible with those tools. 

Don't get confused by things like `choc::com::Ptr<ProgramInterface>` - we have helper classes that use smart pointers like that in the `cmajor/API` folder, but those are just wrappers around the raw COM classes in the `cmajor/COM` folder, and those are all traditional bare pointers with AddRef/Release semantics etc., and if it takes a little bit of tweaking their shape to make them fit the pattern that other tools expect, that's something that we'd be happy to change

**Comment by 0xchase** [comment]
I'm primarily looking to target Rust and possibly Dart (for use with the Flutter framework).

Ah okay, I see. You're right, I was confused by how the smart pointers worked. I assumed it was a fat pointer but now that I've had a closer look at the implementation I see how the reference counting works. So it shouldn't be a problem to implement the Rust interface. I'll let you know if I run into any issues.

**Comment by julianstorer** [comment]
Thanks! Good luck, will be curious to see how you get on..

**Comment by 0xchase** [comment]
I'm going to think it over and give it another go before reopening this issue, though.

**Comment by 0xchase** [comment]
Solved. Got confused about how COM worked, again.

**Comment by 0xchase** [comment]
One thing I noticed... if I call `createEngine`, on an `EngineFactoryInterface` with an *invalid* argument, it seems to throw an exception (the rust runtime fails with the message `fatal runtime error: Rust cannot catch foreign exceptions`). It would be better for interop to return an error code since non C++ code won't be able to catch exceptions like this.

**Comment by julianstorer** [comment]
Ah, if any of our COM methods are throwing, then that's a bug. Thanks for the heads-up, I'll have a look and make sure we trap those..
