### ISSUE TITLE
MIDI Out support? 

### ISSUE THREAD

**Issue by giohappy** [cmajor-lang/cmajor#39]
Is MIDI Out planned? I don't see it mentioned in the document and the examples.

Use cases: MIDI Fx, Sequencers (notes and CC)

**Comment by julianstorer** [comment]
If you build a plugin out of your patch, or load it into the JIT plugin wrapper then it does support MIDI out!

We haven't bothered (yet) to make the VScode extension or command-line tools talk directly to hardware MIDI devices because it would require extra settings to tell it which devices etc, But you could just run the plugin in a DAW and use that to send the MIDI to your gear while you test your patch.

**Comment by giohappy** [comment]
I didn't received Github notification. I'm reading only now @julianstorer.

Thanks, that's great. I will dig more to find out how to generate MIDI outs.
