### ISSUE TITLE
COM API throws exception in setInputFrames

### ISSUE THREAD

**Issue by 0xchase** [cmajor-lang/cmajor#67]
Had some more time to work on Rust bindings to the COM API today. Upon calling `setInputFrames` on a performer Rust subsequently fails to catch a C++ exception. Presumably I'm calling the API incorrectly but my understanding is no exceptions should be thrown regardless.

Adding a `cmaj::catchAllErrors` to `PerformerBase::setInputFrames` and printing it results in the following output:

```
error: Internal compiler error: "getEndpointHandler:808"
```

which you might find helpful in tracking down where the exception is being thrown.

**Comment by cesaref** [comment]
I've just released an updated version of the library, currently in pre-release, which includes a result return code for these operations. The implementation should return failures for these operations rather than raise exceptions (via the assert mechanism).

This should resolve your issue

https://github.com/cmajor-lang/cmajor/releases/tag/1.0.2582
