### ISSUE TITLE
Guarantee representation of Result type

### ISSUE THREAD

**Issue by 0xchase** [cmajor-lang/cmajor#70]
Hello,

In [cmaj_Result.h](https://github.com/cmajor-lang/cmajor/blob/main/include/cmajor/COM/cmaj_Result.h), it's probably appropriate to guarantee the representation of the Result type since the C++ spec (to my knowledge), does not specify how `enums` should be sized and it therefore may vary between compilers or with different compiler flags. What I have in mind is something like:

```
enum class Result: int16_t
{
...
```

Or whatever size you'd prefer. Thanks for all your amazing work!

**Comment by cesaref** [comment]
Yeah, that's a good point - i'll set it to int32_t. I think in practice, since we're using this as a return type the calling convention will keep this in a register, so it will actually not matter what type we specify, but best not to leave anything to chance :)

I'll include this change in the next update.
