### ISSUE TITLE
Loading a file from a plugin

### ISSUE THREAD

**Issue by metakeule** [cmajor-lang/cmajor#82]
How would I load a (in this case) midi file into the generated CLAP or VST plugin to use the data (here: play the midi).

So the idea is, once the hosting DAW stops, I allow the user to select a different file, analyse it etc. and then when the daw is playing, it is only playing (no filesystem access).

**Comment by 0xchase** [comment]
Since (to my knowledge) there isn't an included midi file parser for cmajor and implementing one would be time-consuming, you might want to find a javascript midi file parsing library that will load your file, and then either (1) write the parsed data to a processor endpoint or (2) generate and JIT cmajor code that has the desired midi data embedded into it.

**Comment by julianstorer** [comment]
Yes, that's the right answer. You'd want to do all the offline file handling in javascript, using whatever 3rd party libraries are available for that
